Create a csv file with the county FIPS code and the following county-level census data:
- 2013 and 2023 RUCC
- 2013 and 2024 Urban Influence Code
- Estimated population in poverty 2023
- Estimated percent of population in poverty 2023
- Estimated median income 2023
- Metro/nonmetro delimination 2023
- Unemployment rate in 2023
- Size of civilian labor force 2023',
- Number Employed 2023
- Number Unemployed 2023
- Census population numbers in 2020
- Economic county topology coddes in 2015

All of this data comes from the USDA Economic research service https://www.ers.usda.gov/data-products/county-level-data-sets

In [6]:
import pandas as pd

poverty_df = pd.read_excel('data/Poverty2023.xlsx', dtype={'FIPS_Code': str}, header=4).rename(
    columns = {
        'FIPS_Code': 'FIPS',
    }
)

poverty_columns = ['FIPS', 'Rural_Urban_Continuum_Code_2013',
                   'Urban_Influence_Code_2013',
                   'Rural_Urban_Continuum_Code_2023',
                   'Urban_Influence_Code_2024',
                   'POVALL_2023',
                   'PCTPOVALL_2023',
                   'MEDHHINC_2023',
]

poverty_df_reduc = poverty_df[poverty_columns]

In [7]:
unemployment_df = pd.read_excel('data/Unemployment2023.xlsx', dtype={'FIPS_Code': str}, header=4).rename(
    columns = {
        'FIPS_Code': 'FIPS',
    }
)

unemployment_columns = ['FIPS',
    'Metro_2023',
    'Unemployment_rate_2023',
    'Civilian_labor_force_2023',
    'Employed_2023',
    'Unemployed_2023'
]

unemployment_df_reduc = unemployment_df[unemployment_columns]

In [8]:
population_df = pd.read_excel('data/PopulationEstimates.xlsx', dtype={'FIPStxt': str}, header=4).rename(
    columns = {
        'FIPStxt': 'FIPS',
    }
)

population_columns = ['FIPS', 'CENSUS_2020_POP', 'Economic_typology_2015']

population_df_reduc = population_df[population_columns]

In [9]:
education_df = pd.read_excel('data/Education2023.xlsx', dtype={'FIPS_Code': str}, header=3).rename(
    columns = {
        'FIPS Code': 'FIPS',
    }
)

education_df

,FIPS,State,Area name,2013 Urban Influence Code,2024 Urban Influence Code,2013 Rural-urban Continuum Code,2023 Rural-urban Continuum Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,"Percent of adults completing some college or associate degree, 2008-12","Percent of adults with a bachelor's degree or higher, 2008-12","Less than high school graduate, 2019-23","High school graduate (or equivalency), 2019-23","Some college or associate degree, 2019-23","Bachelor's degree or higher, 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23"
0,0,US,United States,NaN,NaN,NaN,NaN,52373312.0,34158051.0,11650730.0,...,28.993579,28.484955,24230217.0,59836489.0,64413653.0,79954302.0,10.607067,26.194137,28.197846,35.000950
1,1000,AL,Alabama,NaN,NaN,NaN,NaN,1062306.0,468269.0,136287.0,...,29.022866,22.264896,409381.0,1046374.0,1035466.0,957081.0,11.871959,30.344616,30.028286,27.755139
2,1001,AL,Autauga County,2.0,4.0,2.0,2.0,6611.0,3757.0,933.0,...,29.618142,21.707831,3963.0,13321.0,11953.0,11530.0,9.721098,32.675939,29.320284,28.282680
3,1003,AL,Baldwin County,2.0,4.0,3.0,3.0,18726.0,8426.0,2334.0,...,31.819503,27.741591,14221.0,47369.0,53990.0,56408.0,8.268600,27.542038,31.391725,32.797637
4,1005,AL,Barbour County,6.0,5.0,6.0,6.0,8120.0,2242.0,581.0,...,25.771784,14.524286,3911.0,6629.0,5067.0,2021.0,22.186295,37.604947,28.744044,11.464715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,72145,PR,Vega Baja Municipio,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,23.959976,17.584094,9038.0,11614.0,9506.0,10025.0,22.492099,28.902770,23.656770,24.948361
3290,72147,PR,Vieques Municipio,12.0,3.0,7.0,6.0,NaN,NaN,NaN,...,15.886045,10.140029,1815.0,2872.0,590.0,745.0,30.139489,47.691797,9.797409,12.371305
3291,72149,PR,Villalba Municipio,2.0,4.0,2.0,2.0,NaN,NaN,NaN,...,14.340816,15.207082,3295.0,4970.0,3814.0,3503.0,21.146194,31.895777,24.476961,22.481068
3292,72151,PR,Yabucoa Municipio,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,19.986177,12.912144,5722.0,5818.0,6775.0,4119.0,25.505929,25.933850,30.199697,18.360524
3293,72153,PR,Yauco Municipio,2.0,4.0,2.0,2.0,NaN,NaN,NaN,...,17.759937,16.795075,5193.0,8609.0,4674.0,6874.0,20.485207,33.960552,18.437870,27.116371

In [10]:
all_data = pd.merge(population_df_reduc, poverty_df_reduc, on='FIPS')
all_data = pd.merge(all_data, unemployment_df_reduc, on='FIPS')

all_data.head()

,FIPS,CENSUS_2020_POP,Economic_typology_2015,Rural_Urban_Continuum_Code_2013,Urban_Influence_Code_2013,Rural_Urban_Continuum_Code_2023,Urban_Influence_Code_2024,POVALL_2023,PCTPOVALL_2023,MEDHHINC_2023,Metro_2023,Unemployment_rate_2023,Civilian_labor_force_2023,Employed_2023,Unemployed_2023
0,00000,331449281.0,NaN,NaN,NaN,NaN,NaN,40763043.0,12.5,77719.0,NaN,3.6,166689556.0,160623678.0,6065878.0
1,01000,5024279.0,NaN,NaN,NaN,NaN,NaN,780043.0,15.7,62248.0,NaN,2.5,2308131.0,2250472.0,57659.0
2,01001,58805.0,0.0,2.0,2.0,2.0,4.0,7004.0,11.7,68857.0,1.0,2.2,27000.0,26409.0,591.0
3,01003,231767.0,5.0,3.0,2.0,3.0,4.0,24942.0,10.0,74248.0,1.0,2.3,104409.0,102029.0,2380.0
4,01005,25223.0,3.0,6.0,6.0,6.0,5.0,5585.0,25.5,45298.0,0.0,4.4,7944.0,7592.0,352.0

In [11]:
all_data.to_csv("../data/county_characteristics.csv", index=False)